declare var require:any;
export const CODE_SNIPPETS={
"./docs/angular/akhram.md":require('./docs/angular/akhram.md'),
"./docs/angular/debounce.md":require('./docs/angular/debounce.md'),
"./docs/angular/http-interceptor.md":require('./docs/angular/http-interceptor.md'),
"./docs/dom/dom-handler.md":require('./docs/dom/dom-handler.md'),
"./docs/dom/dom-operations.md":require('./docs/dom/dom-operations.md'),
"./docs/dom/dom-utils.md":require('./docs/dom/dom-utils.md'),
"./docs/dom/scroll-table-column.md":require('./docs/dom/scroll-table-column.md'),
"./docs/dom/scrollable-sidebar.md":require('./docs/dom/scrollable-sidebar.md'),
"./docs/file-3.md":require('./docs/file-3.md'),
"./docs/folder-1/file-1.1.md":require('./docs/folder-1/file-1.1.md'),
"./docs/folder-1/file-1.2.md":require('./docs/folder-1/file-1.2.md'),
"./docs/linux/ssh.md":require('./docs/linux/ssh.md'),
"./docs/misc/corporate-proxy.md":require('./docs/misc/corporate-proxy.md'),
"./docs/misc/git-commands.md":require('./docs/misc/git-commands.md'),
"./docs/misc/jekyll.md":require('./docs/misc/jekyll.md'),
"./docs/misc/jira-issue-filter.md":require('./docs/misc/jira-issue-filter.md'),
"./docs/regex/camelcase.md":require('./docs/regex/camelcase.md'),
"./docs/scss/box-shadow.md":require('./docs/scss/box-shadow.md'),
"./docs/venkat.md":require('./docs/venkat.md'),
}